### ISSUE TITLE
Typo in package name in the warning

### ISSUE THREAD

**Issue by funkycode** [funtoo/boot-update#13]
The warning is:
  * WARN: Intel system detected - please emerge sys-firmware/intel-microcode and sys-apps/iucode-tool and run boot-update again; boot-update will then patch your system with the latest Intel CPU and
          chipset microcode patches at boot-time, protecting you against important vulnerabilities and errata.

it should be sys-apps/iucode_tool

**Comment by angryvincent** [comment]
corrected now
